# EDA TP Grupo N°13 — Yellow Taxi NYC (26Co2026)

Análisis exploratorio simple.

Integrantes:
- F, Rocío
- Lerner, Federico
- Makk, Azul
- Moguilner Reh, Nicolás
- Varela, Gustavo

In [6]:
from pathlib import Path

import pandas as pd

DATA_PATH = Path("dataset") / "yellow_tripdata_2026-03.parquet"
df = pd.read_parquet(DATA_PATH)
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,2,2026-03-01 00:02:26,2026-03-01 00:13:45,1.0,2.58,1.0,N,48,151,1,14.2,1.0,0.5,4.99,0.0,1.0,24.94,2.5,0.0,0.75
1,2,2026-03-01 00:19:33,2026-03-01 00:28:21,1.0,1.50,1.0,N,238,166,1,10.0,1.0,0.5,0.00,0.0,1.0,15.00,2.5,0.0,0.00
2,2,2026-03-01 00:07:20,2026-03-01 00:15:12,2.0,0.88,1.0,N,90,249,1,8.6,1.0,0.5,2.87,0.0,1.0,17.22,2.5,0.0,0.75
3,2,2026-03-01 00:16:11,2026-03-01 00:28:20,1.0,1.76,1.0,N,249,137,1,12.1,1.0,0.5,3.57,0.0,1.0,21.42,2.5,0.0,0.75
4,2,2026-03-01 00:20:47,2026-03-01 00:30:44,2.0,1.57,1.0,N,100,142,1,11.4,1.0,0.5,3.43,0.0,1.0,20.58,2.5,0.0,0.75

In [7]:
print("Filas, columnas:", df.shape)
df.dtypes

Filas, columnas: (3952451, 20)

VendorID                          int32
tpep_pickup_datetime     datetime64[us]
tpep_dropoff_datetime    datetime64[us]
passenger_count                 float64
trip_distance                   float64
RatecodeID                      float64
store_and_fwd_flag               object
PULocationID                      int32
DOLocationID                      int32
payment_type                      int64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
improvement_surcharge           float64
total_amount                    float64
congestion_surcharge            float64
Airport_fee                     float64
cbd_congestion_fee              float64
dtype: object

In [8]:
df.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3952451 entries, 0 to 3952450
Data columns (total 20 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int32
 1   tpep_pickup_datetime   datetime64[us]
 2   tpep_dropoff_datetime  datetime64[us]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     object
 7   PULocationID           int32
 8   DOLocationID           int32
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  Airport_fee            float64
 19  cbd_congestion_fee     float64
dtypes: datetime64[us](2), float64(13), int32(3), int64(1), object(1)
memory usage: 692.7 MB

In [9]:
df.describe(include="all")

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
count,3.952451e+06,3952451,3952451,3.006703e+06,3.952451e+06,3.006703e+06,3006703,3.952451e+06,3.952451e+06,3.952451e+06,3.952451e+06,3.952451e+06,3.952451e+06,3.952451e+06,3.952451e+06,3.952451e+06,3.952451e+06,3.006703e+06,3.006703e+06,3.952451e+06
unique,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,NaN,NaN,NaN,NaN,3001767,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,1.877893e+00,2026-03-16 09:09:15.947559,2026-03-16 09:26:33.369682,1.230823e+00,5.983693e+00,5.635411e+00,NaN,1.615081e+02,1.608602e+02,8.805670e-01,2.132742e+01,1.115754e+00,4.885423e-01,2.857518e+00,5.283688e-01,9.521509e-01,3.009739e+01,2.187603e+00,1.556437e-01,5.297510e-01
min,1.000000e+00,2008-12-31 23:03:20,2009-01-01 00:07:36,0.000000e+00,0.000000e+00,1.000000e+00,NaN,1.000000e+00,1.000000e+00,0.000000e+00,-9.900000e+02,-7.500000e+00,-5.000000e-01,-7.575000e+01,-1.117900e+02,-1.000000e+00,-1.022460e+03,-2.500000e+00,-2.000000e+00,-7.500000e-01
25%,2.000000e+00,2026-03-08 17:38:26,2026-03-08 17:55:32,1.000000e+00,1.010000e+00,1.000000e+00,NaN,1.140000e+02,1.070000e+02,1.000000e+00,1.000000e+01,0.000000e+00,5.000000e-01,0.000000e+00,0.000000e+00,1.000000e+00,1.722000e+01,2.500000e+00,0.000000e+00,0.000000e+00
50%,2.000000e+00,2026-03-16 08:13:05,2026-03-16 08:32:14,1.000000e+00,1.820000e+00,1.000000e+00,NaN,1.610000e+02,1.620000e+02,1.000000e+00,1.560000e+01,0.000000e+00,5.000000e-01,2.110000e+00,0.000000e+00,1.000000e+00,2.340000e+01,2.500000e+00,0.000000e+00,7.500000e-01
75%,2.000000e+00,2026-03-23 17:55:51.500000,2026-03-23 18:13:19,1.000000e+00,3.710000e+00,1.000000e+00,NaN,2.330000e+02,2.340000e+02,1.000000e+00,2.680000e+01,2.500000e+00,5.000000e-01,3.950000e+00,0.000000e+00,1.000000e+00,3.490000e+01,2.500000e+00,0.000000e+00,7.500000e-01
max,7.000000e+00,2026-04-01 00:06:25,2026-04-02 16:03:47,8.000000e+00,2.883817e+05,9.900000e+01,NaN,2.650000e+02,2.650000e+02,4.000000e+00,1.843300e+03,1.746000e+01,4.750000e+00,3.970000e+02,1.400000e+03,1.000000e+00,1.850550e+03,2.500000e+00,2.700000e+01,7.500000e-01
std,7.248573e-01,NaN,NaN,6.330375e-01,5.810545e+02,2.059152e+01,NaN,6.656641e+01,7.070784e+01,6.317968e-01,1.868689e+01,1.746227e+00,9.035171e-02,3.914010e+00,2.285484e+00,2.360685e-01,2.241197e+01,8.683972e-01,5.548265e-01,3.473906e-01

In [10]:
nulos = df.isna().sum().sort_values(ascending=False)
nulos[nulos > 0]

Airport_fee             945748
passenger_count         945748
congestion_surcharge    945748
RatecodeID              945748
store_and_fwd_flag      945748
dtype: int64